###服务启动端口号
server:
  port: 8001
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: app-wangmeng-order
###服务注册到eureka地址
#eureka:
#  client:
#    service-url:
#           defaultZone: http://localhost:8100/eureka
###集群地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka,http://localhost:9100/eureka
    ###因为该应用为注册中心，不会注册自己
    register-with-eureka: true
    ###是否需要从eureka上获取注册信息
    fetch-registry: true