###服务启动端口号
server:
  port: 8011
  tomcat:
    max-threads: 10
###服务名称(服务注册到eureka名称)  
spring:
    application:
        name: app-wangmeng-order
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka

           
###因为该应用为注册中心，不会注册自己
    register-with-eureka: true
###是否需要从eureka上获取注册信息
    fetch-registry: true
###设置feign客户端超时时间
ribbon:
  ###指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间。
  ReadTimeout: 5000
  ###指的是建立连接后从服务器读取到可用资源所用的时间。
  ConnectTimeout: 5000
feign:
  hystrix:
    enabled: true
##### hystrix禁止服务超时时间
hystrix:
 command:
   default:
      execution:
       timeout:
        enabled: true